# Generated by Django 5.1.1 on 2024-09-06 14:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_delete_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="friend",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="friend",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="friendrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
